### ISSUE TITLE
class QueryCompilerText extends Minitest::Test

### ISSUE THREAD

**Issue by peterc** [mattbrictson/minitest-snapshots#25]
Typo in the README?

```
class QueryCompilerText extends Minitest::Test
```

**Comment by mattbrictson** [comment]
Great catch, thanks! 😅

**Comment by peterc** [comment]
I did have to double check that Ruby hadn't smuggled in some fancy new syntax in a recent build or something. I've been doing a lot of Python lately.. 😆
