### ISSUE TITLE
Is this gem still under active development?

### ISSUE THREAD

**Issue by natachatomkinson** [mattbrictson/minitest-snapshots#8]
:wave:

If this gem is still active, is it ok to post PRs i.e. do the authors still have time to review?

I would be happy to look at updating the dependencies for a start but I would feel more confident if the branch `tests` was merged into `main` first and foremost.

I have to assume there is a different hidden workflow to deploy your gem, would you be interested in moving that to github actions?

Either way, let me know! :)

**Comment by mattbrictson** [comment]
Hi @natachatomkinson!

> If this gem is still active, is it ok to post PRs i.e. do the authors still have time to review?

Yes, I am taking over as maintainer hope to be able to review PRs.

> I would feel more confident if the branch `tests` was merged into `main` first and foremost

Thanks for the heads-up! I'll make that one of my first priorities.

> I have to assume there is a different hidden workflow to deploy your gem

I plan on manually running `rake release` (the standard gem publishing tasks built into bundler) and will use GitHub Releases to track versions and release notes.

**Comment by mattbrictson** [comment]
The `tests` branch has been [merged](https://github.com/mattbrictson/minitest-snapshots/pull/12) ✅

**Comment by mattbrictson** [comment]
I've released minitest-snapshots 1.0.0. I'll close this issue.
